
# Consul version to install
consul_version: "1.20.1"

# Consul Download url
consul_url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip

# Specify the datacenter the agent is a member of
consul_datacenter: jeddah

#temporary download location
consul_download_dir: /tmp

# Directory where the Consul binary will be installed
consul_install_dir: "/usr/local/bin"

# Directory for Consul configuration files
consul_config_dir: "/etc/consul.d"

# Systemd Service Name
consul_service_name: consul

# Consul systemd service file location
consul_service_file: "/etc/systemd/system/consul.service"

# Consul data directory for storing state
consul_data_dir: "/etc/consul/data"

# Consul user and group (created for running the service)
consul_user: "consul"
consul_group: "consul"

# Encryption key used my consul servers - to secure the identities
# Generate a 32-byte (256-bit) base64-encoded key
# openssl rand -base64 32
# echo "<key>" | base64 -d | wc -c
consul_encryption_key: 

consul_advertise_addr: 

# Address to bind Consul to (use 0.0.0.0 to bind to all interfaces)
consul_bind_addr: "0.0.0.0"

# Consul server settings
consul_server: true
consul_bootstrap_expect: 3

# UI settings
consul_ui: true

# Retry join addresses (empty by default, to be filled with other nodes)
consul_retry_join:
  - "172.21.179.11"
  - "172.21.179.12"
  - "172.21.179.13"
