
- name: Create Consul group
  group: name={{ consul_group }} system=yes state=present

- name: Create Consul user
  user: >
    name={{ consul_user }}
    shell=/bin/false
    createhome=no
    group={{ consul_group }}
    system=yes
    state=present

- name: Ensure unzip is installed (required by unarchive module)
  yum: name=unzip state=installed

- name: Download Consul
  get_url: >
    url={{ consul_url }}
    dest={{ consul_download_dir }}/consul{{ consul_version }}.zip

- name: Unzip Consul to installation directory
  command: unzip -o {{ consul_download_dir }}/consul{{ consul_version }}.zip -d {{ consul_install_dir }}
  args:
    creates: "{{ consul_install_dir }}/consul{{ consul_version }}"

- name: Set consul to link to installed version
  file: >
    src="{{ consul_install_dir }}/consul"
    dest="{{ consul_install_dir }}/consul{{ consul_version }}"
    state=link

- name: Create Consul configuration directory
  file: >
    path={{ consul_config_dir }}
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
    state=directory

- name: If consul.service configuration already exists, remove it
  file: >
    state=absent
    path=/etc/systemd/system/consul.service

- name: Create consul_server.service configuration
  template: >
    src=consul_server.service.j2
    dest=/etc/systemd/system/consul.service
    owner=root
    group=root
    mode=0644
  notify: restart consul
  when: inventory_hostname in groups['consul_servers']


- name: Create consul_client.service configuration
  template: >
    src=consul_client.service.j2
    dest=/etc/systemd/system/consul.service
    owner=root
    group=root
    mode=0644
  notify: restart consul
  when: inventory_hostname in groups['consul_clients']

- name: Create Consul server configuration file
  template: >
    src=consul_server.hcl.j2
    dest={{ consul_config_dir }}/server.hcl
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0644
  notify: restart consul
  when: inventory_hostname in groups['consul_servers']

- name: Create Consul client configuration file
  template: >
    src=consul_client.hcl.j2
    dest={{ consul_config_dir }}/client.hcl
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0644
  notify: restart consul
  when: inventory_hostname in groups['consul_clients']

- name: Ensure Consul service is started and enabled on boot
  service: name={{ consul_service_name }} state=started enabled=yes
