- name: restart nomad
  service: name={{ nomad_service_name }} state=restarted

- name: reload nomad
  service: name={{ nomad_service_name }} state=reloaded

- name: Reload systemd
  command: systemctl daemon-reload