all:
  children:
    vms:
      hosts: 
        vm1:
          ansible_host: 172.27.9.93
        vm2:
          ansible_host: 172.27.9.35
        vm3:
          ansible_host: 172.27.9.247
        vm4:
          ansible_host: 172.27.9.196
        vm5:
          ansible_host: 172.27.9.192
        vm6:
          ansible_host: 172.27.9.47

    nomad_servers:
      hosts:
        nomad-server-1:
          ansible_host: 172.27.9.93
          role_type: "server"
        nomad-server-2:
          ansible_host: 172.27.9.35
          role_type: "server"
        nomad-server-3:
          ansible_host: 172.27.9.247
          role_type: "server"

    nomad_clients:
      hosts:
        nomad-client-1:
          ansible_host: 172.27.9.196
          java_version: "17"
          role_type: "client"
        nomad-client-2:
          ansible_host: 172.27.9.192
          java_version: "21"
          role_type: "client"
        nomad-client-3:
          ansible_host: 172.27.9.47
          java_version: "21"
          role_type: "client"

    consul_servers:
      hosts:
        consul-server-1:
          ansible_host: 172.27.9.93
          role_type: "server"
        consul-server-2:
          ansible_host: 172.27.9.35
          role_type: "server"
        consul-server-3:
          ansible_host: 172.27.9.247
          role_type: "server"

    consul_clients:
      hosts:
        consul-client-1:
          ansible_host: 172.27.9.196
          role_type: "client"
        consul-client-2:
          ansible_host: 172.27.9.192
          role_type: "client"
        consul-client-3:
          ansible_host: 172.27.9.47
          role_type: "client"
