all:
  children:
    vms:
      hosts: 
        vm1:
          ansible_host: 172.21.179.11
        vm2:
          ansible_host: 172.21.179.12
        vm3:
          ansible_host: 172.21.179.13
        vm4:
          ansible_host: 172.21.179.21
        vm5:
          ansible_host: 172.21.179.22
        vm6:
          ansible_host: 172.21.179.23

    nomad_servers:
      hosts:
        nomad-server-1:
          ansible_host: 172.21.179.11
          role_type: "server"
        nomad-server-2:
          ansible_host: 172.21.179.12
          role_type: "server"
        nomad-server-3:
          ansible_host: 172.21.179.13
          role_type: "server"

    nomad_clients:
      hosts:
        nomad-client-1:
          ansible_host: 172.21.179.21
          java_version: "17"
          role_type: "client"
        nomad-client-2:
          ansible_host: 172.21.179.22
          java_version: "21"
          role_type: "client"
        nomad-client-3:
          ansible_host: 172.21.179.23
          java_version: "21"
          role_type: "client"

    consul_servers:
      hosts:
        consul-server-1:
          ansible_host: 172.21.179.11
          role_type: "server"
        consul-server-2:
          ansible_host: 172.21.179.12
          role_type: "server"
        consul-server-3:
          ansible_host: 172.21.179.13
          role_type: "server"

    consul_clients:
      hosts:
        consul-client-1:
          ansible_host: 172.21.179.21
          role_type: "client"
        consul-client-2:
          ansible_host: 172.21.179.22
          role_type: "client"
        consul-client-3:
          ansible_host: 172.21.179.23
          role_type: "client"
