- name: restart consul
  service: name={{ consul_service_name }} state=restarted

- name: reload nomad
  service: name={{ consul_service_name }} state=reloaded

- name: Reload systemd
  command: systemctl daemon-reload