---
- name: Install common dependencies
  become: true
  block:
    - name: Ensure required packages are installed
      dnf:
        name:
          - unzip
          - wget
          - curl
          - firewalld
          - systemd
          - java-17-openjdk
          - java-21-openjdk
        state: present
        update_cache: true

    - name: Ensure Java 17 directory exists
      file:
        path: "{{ nomad_clients_java_versions['17'] }}"
        state: directory
    
    - name: Find the exact Java 17 directory
      command: ls -d /usr/lib/jvm/java-17-openjdk-*
      register: java_17_path
      changed_when: false

    - name: Create symbolic link for Java 17
      file:
        path: "{{ nomad_clients_java_versions['17'] }}"
        src: "{{ java_17_path.stdout }}"
        state: link

    - name: Ensure Java 21 directory exists
      file:
        path: "{{ nomad_clients_java_versions['21'] }}"
        state: directory

    - name: Find the exact Java 21 directory
      command: ls -d /usr/lib/jvm/java-21-openjdk-*
      register: java_21_path
      changed_when: false

    - name: Create symbolic link for Java 21
      file:
        path: "{{ nomad_clients_java_versions['21'] }}"
        src: "{{ java_21_path.stdout }}"
        state: link

    - name: Start and enable firewalld
      systemd:
        name: firewalld
        enabled: true
        state: started

    - name: Open necessary ports in the firewall
      command: >
        firewall-cmd --add-port={{ item }} --permanent
      loop:
        - "4646/tcp"
        - "4647/tcp"
        - "8300/tcp"
        - "8301/tcp"
        - "8301/udp"
        - "8500/tcp"
        - "8600/tcp"
        - "8600/udp"

    - name: Reload firewall to apply changes
      command: firewall-cmd --reload

