---
- name: Install common dependencies
  become: true
  block:
    - name: Ensure required packages are installed
      dnf:
        name:
          - unzip
          - wget
          - curl
          - firewalld
          - systemd
          - java-17-openjdk
          - java-21-openjdk
        state: present
        update_cache: true

    - name: Start and enable firewalld
      systemd:
        name: firewalld
        enabled: true
        state: started

    - name: Add necessary ports to firewall
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: present
      loop:
        - "4646/tcp"
        - "4647/tcp"
        - "8300/tcp"
        - "8301/tcp"
        - "8301/udp"
        - "8500/tcp"
        - "8600/tcp"
        - "8600/udp"

    - name: Reload firewall to apply changes
      firewalld:
        state: reloaded
