---
- name: Install common dependencies
  become: true
  block:
    - name: Ensure required packages are installed
      dnf:
        name:
          - unzip
          - wget
          - curl
          - firewalld
          - systemd
          - java-17-openjdk
          - java-21-openjdk
          - docker
        state: present
        update_cache: true

    - name: Start and enable firewalld
      systemd:
        name: firewalld
        enabled: true
        state: started

    - name: Open necessary ports in the firewall
      command: >
        firewall-cmd --add-port={{ item }} --permanent
      loop:
        - "4646/tcp"
        - "4647/tcp"
        - "8300/tcp"
        - "8301/tcp"
        - "8301/udp"
        - "8500/tcp"
        - "8600/tcp"
        - "8600/udp"

    - name: Reload firewall to apply changes
      command: firewall-cmd --reload

